//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyAwayPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public decimal photoID { get; set; }
        public string url { get; set; }
        public string dateCreated { get; set; }
    }
}
